
import React from 'react';
import { LoadingSpinner, ErrorIcon, ImageIcon, DownloadIcon } from './icons';

interface ImageDisplayProps {
  imageUrl: string | null;
  isLoading: boolean;
  error: string | null;
  onDownload: () => void;
}

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, error, onDownload }) => {
  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="flex flex-col items-center justify-center gap-4">
          <LoadingSpinner />
          <p className="text-lg text-gray-400">Generating your vision...</p>
        </div>
      );
    }
    if (error) {
      return (
        <div className="flex flex-col items-center justify-center gap-4 text-red-400">
          <ErrorIcon />
          <p className="text-lg font-semibold">Generation Failed</p>
          <p className="text-center text-sm">{error}</p>
        </div>
      );
    }
    if (imageUrl) {
      return (
        <img
          src={imageUrl}
          alt="Generated by Gemini"
          className="max-w-full max-h-full object-contain rounded-lg shadow-lg"
        />
      );
    }
    return (
      <div className="flex flex-col items-center justify-center gap-4 text-gray-500">
        <ImageIcon className="w-24 h-24" />
        <p className="text-xl font-medium">Your image will appear here</p>
        <p className="text-center">Enter a prompt and click "Generate" to start creating.</p>
      </div>
    );
  };

  return (
    <div className="relative flex-grow flex items-center justify-center bg-gray-800/50 rounded-lg border-2 border-dashed border-gray-700 p-4 aspect-square">
      {renderContent()}
      {imageUrl && !isLoading && !error && (
        <button
          onClick={onDownload}
          className="absolute top-4 right-4 bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-full inline-flex items-center gap-2 transition-transform duration-200 transform hover:scale-105 shadow-lg"
          aria-label="Download image"
        >
          <DownloadIcon />
          <span>Download</span>
        </button>
      )}
    </div>
  );
};
